[package]
name = "indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
dotenvy = "0.15.7"
eth_client = { path = "../eth_client" }
tokio = { version = "1.46.1", features = ["full"] }
