name: CI/CD

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main

jobs:
  pr_checks:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Run cargo check
        run: cargo check

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings

      - name: Run cargo fmt check
        run: cargo fmt -- --check

      - name: Run cargo test
        run: cargo test
        env:
          JSON_RPC_API_KEY: ${{ secrets.JSON_RPC_API_KEY }}

  build_and_push_docker:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: your-dockerhub-username/blockchain-indexer:latest
          file: ./Dockerfile
